// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhrborlmwhpsdjbrihox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocmJvcmxtd2hwc2RqYnJpaG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTgzNDIsImV4cCI6MjA2NTQ3NDM0Mn0.iXgnt9DJkQY1ZxhIlZQHS4vc3QFx808qX5C2btaIrn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);